const lessons = [
  {
    id: 1,
    subject: "Martial Arts",
    location: "Knowledge Park",
    price: 500,
    availableSpace: 5,
    image: "images/martial_arts.png",
  },
  {
    id: 2,
    subject: "Coding Club",
    location: "Academic City",
    price: 200,
    availableSpace: 5,
    image: "images/coding.png",
  },
  {
    id: 3,
    subject: "Dance Class",
    location: "Festival City",
    price: 350,
    availableSpace: 5,
    image: "images/dance.png",
  },
  {
    id: 4,
    subject: "Debate Team",
    location: "Academic City",
    price: 350,
    availableSpace: 5,
    image: "images/debate.png",
  },
  {
    id: 5,
    subject: "Yoga Class",
    location: "Al Safa",
    price: 500,
    availableSpace: 5,
    image: "images/yoga.png",
  },
  {
    id: 6,
    subject: "Science Club",
    location: "Knowledge Park",
    price: 250,
    availableSpace: 5,
    image: "images/science.png",
  },
  {
    id: 7,
    subject: "Photography Club",
    location: "Festival City",
    price: 700,
    availableSpace: 5,
    image: "images/photography.png",
  },
  {
    id: 8,
    subject: "Art Class",
    location: "Al Safa",
    price: 300,
    availableSpace: 5,
    image: "images/art.png",
  },
  {
    id: 9,
    subject: "Academic Tutoring",
    location: "Knowledge Park",
    price: 500,
    availableSpace: 5,
    image: "images/academic_tutoring.png",
  },
  {
    id: 10,
    subject: "Creative Writing",
    location: "Academic City",
    price: 250,
    availableSpace: 5,
    image: "images/creative_writing.png",
  },
];
